### ISSUE TITLE
How to run it in Windows ?

### ISSUE THREAD

**Issue by mlotfi2005** [testhive/Cucumber-Capybara-Template#1]
Hi,
because you have some sh script, I can't run it in windows, 

C:\Cucumber-Capybara-Template
λ  docker-test.run.sh
The term 'docker-test.run.sh' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a  path was included, verify that the path is correct and try again.
At line:1 char:19
+ docker-test.run.sh <<<<
    + CategoryInfo          : ObjectNotFound: (docker-test.run.sh:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

C:\Cucumber-Capybara-Template
λ  docker build  -t longlost/cukes-template .
ERRO[0000] failed to dial gRPC: cannot connect to the Docker daemon. Is 'docker daemon' running on this host?: open //./pipe/docker_engine: The system cannot find the file specified.
error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.33/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&session=46e19a4f5101353dd2d26a01da79979e4d87154fe4b50dec86870c2653a3a054&shmsize=0&t=longlost%2Fcukes-template&target=&ulimits=null: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
C:\Cucumber-Capybara-Template

Thanks,

**Comment by mlotfi2005** [comment]
How to run this project ?????

**Comment by testhive** [comment]
Hi, at the moment for docker runs, the project only supports Linux and MacOS. For running individual feature files on Windows, please refer to the Readme.
